# Dockerfile for testing
FROM maven:3.9.3-eclipse-temurin-20 AS builder

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean install -DskipTests
RUN mvn package -DskipTests

# Use the same base image as before
FROM eclipse-temurin:20-jdk-alpine

WORKDIR /app

# Copy the project files to run tests inside this container
COPY --from=builder /app .

RUN apk add --no-cache maven

# Run tests (you can also manually trigger the tests from inside)
CMD ["mvn", "test"]